[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/es/*"
  to = "/es/404"
  status = 404

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        Access-Control-Allow-Origin = "*"
        cache-control = '''
            max-age=0, 
            no-cache, 
            no-store, 
            must-revalidate'''

